name: Android CI[PR

on:
  pull_request:
    paths-ignore:
      - .gitignore

jobs:
  buildApkFile:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Allow gradlew permission
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug
          
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: DrangonIDE Apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload output metadata APK
        uses: actions/upload-artifact@v4
        with:
          name: Output Metadata
          path: app/build/outputs/apk/debug/output-metadata.json
